project:
  type: website
  output-dir: docs
  
website:
  title: "Cold Reflections"
  favicon: "coldreflection.jpeg"
  navbar:
    logo: "coldreflection.jpeg"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quirtt
format:
  html:
    # theme: pulse
    # theme: cerulean
    theme: default
    # theme: cyborg
    # theme: minty
    # theme: sketchy
    # theme: vapor (blue edit karna padega)
  
    css: styles.css



