project:
  type: website
  output-dir: docs
  
website:
  title: "pls suggest name"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quirtt
format:
  html:
    theme: solar
    css: styles.css



