project:
  type: website
  output-dir: docs
  resources: 
    - thoughts/

website:
  title: "Cold Reflections"
  favicon: "coldreflection.jpeg"
  navbar:
    logo: "coldreflection.jpeg"
    left:
      - text: "Thoughts"
        href: thoughts/


    right:
      - about.qmd
      - icon: github
        href: https://github.com/quirtt
format:
  html:
    theme: pulse
    css: styles.css



