project:
  type: website
  output-dir: docs
  
website:
  title: "smth smth math smth smth cs smth smth logic"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/quirtt
format:
  html:
    theme: cosmo
    css: styles.css



